// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuDEx9atWqjDQVxG6CxxlrBDkgYCyxaYo',
    appId: '1:1058287661455:web:2687eec5b8bca82714dbfa',
    messagingSenderId: '1058287661455',
    projectId: 'diabetescare-43a77',
    authDomain: 'diabetescare-43a77.firebaseapp.com',
    storageBucket: 'diabetescare-43a77.firebasestorage.app',
    measurementId: 'G-BP0S3DF2RQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBK-9Oxd_ZGg8lOUEp9mUQNkUk7Aos-Pdk',
    appId: '1:1058287661455:android:dbe52192dd21f6fc14dbfa',
    messagingSenderId: '1058287661455',
    projectId: 'diabetescare-43a77',
    storageBucket: 'diabetescare-43a77.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_92hT8_ga45qojtLPi4_xjSS3fHCFsnc',
    appId: '1:1058287661455:ios:a1e8974af3e48ea314dbfa',
    messagingSenderId: '1058287661455',
    projectId: 'diabetescare-43a77',
    storageBucket: 'diabetescare-43a77.firebasestorage.app',
    iosBundleId: 'com.example.diabetesCare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_92hT8_ga45qojtLPi4_xjSS3fHCFsnc',
    appId: '1:1058287661455:ios:a1e8974af3e48ea314dbfa',
    messagingSenderId: '1058287661455',
    projectId: 'diabetescare-43a77',
    storageBucket: 'diabetescare-43a77.firebasestorage.app',
    iosBundleId: 'com.example.diabetesCare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuDEx9atWqjDQVxG6CxxlrBDkgYCyxaYo',
    appId: '1:1058287661455:web:10a6fb3e04c9e0ba14dbfa',
    messagingSenderId: '1058287661455',
    projectId: 'diabetescare-43a77',
    authDomain: 'diabetescare-43a77.firebaseapp.com',
    storageBucket: 'diabetescare-43a77.firebasestorage.app',
    measurementId: 'G-55V078W5XP',
  );
}
